### NN implementaion in numpy (one epoch)

In [0]:
import numpy as np

In [0]:
#Step0 : Inputs & Outputs
#X = raw_input("Enter the inputs of size (n,m)")
X = np.array(([1, 0, 1, 0], [1, 0, 1, 1], [0, 1, 0, 1]), dtype=float)
#Y = raw_input("Enter their respective outputs of size (1,m)")
Y = np.array(([1], [1], [0]), dtype=float).reshape(3,-1)

In [0]:
#Step1 : initializing weights and biases
wh = np.random.randn(4, 3) #hidden layer
wout = np.random.randn(3, 1) #output layer
bh = np.random.randn(1,3)
bout = np.random.randn(1, 1)

In [0]:
#Step2 : Calculate the hidden_layer_input
hidden_layer_input = X.dot(wh) + bh #linear function

In [0]:
#Step3 : Perform non-linear transformation(sigmoid) on hidden_linear_input to get hidden_layer_activations.
def sigmoid(x):
  return (1 / (1 + np.exp(x)))
hidden_layer_activations = sigmoid(hidden_layer_input)

In [0]:
#Step4 : Perform linear and non-linear transformation of hidden layer activation at output layer
output_layer_input = hidden_layer_activations.dot(wout) + bout
output = sigmoid(output_layer_input)

In [0]:
#Step5 : Calculate gradient of Error(E) at output layer
E = Y - output

In [0]:
#Step6: Compute slope at output and hidden layer (local gradients)
def derivatives_sigmoid(x):
  return (x * (1-x))
slope_output_layer = derivatives_sigmoid(output)
slope_hidden_layer = derivatives_sigmoid(hidden_layer_activations)

In [0]:
#Step7: Compute delta at output layer
lr = 0.1
d_output = E * slope_output_layer*lr

In [0]:
#Step8: Calculate Error at hidden layer
Error_at_hidden_layer = d_output * np.transpose(wout)

In [0]:
#Step9: Compute delta at hidden layer
d_hidden_layer = Error_at_hidden_layer * slope_hidden_layer

In [0]:
#Step10: Update weight at both output and hidden layer
wout = wout + (np.transpose(hidden_layer_activations).dot(d_output)) * lr
wh = wh+ (np.transpose(X).dot(d_hidden_layer)) * lr

In [0]:
#Step 11: Update biases at both output and hidden layer
bh = bh + np.sum(d_hidden_layer, axis=0) * lr
bout = bout + np.sum(d_output, axis=0)* lr

In [98]:
print(wout)

[[0.03683514]
 [0.09133147]
 [1.12177701]]


In [100]:
print(wout)

[[0.03818756]
 [0.09355935]
 [1.12379065]]


![alt text](https://i.ytimg.com/vi/yTFc7uCZG5k/maxresdefault.jpg)

In [0]:
################
KERAS
################
from keras.models import Sequential
from keras.layers.core import Dense, Activation
from keras.optimizers import SGD
import numpy as np 

In [0]:
X = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[0],[1],[1],[0]])

In [0]:
model_keras = Sequential()
model_keras.add(Dense(8, input_dim=2))
model_keras.add(Activation('relu'))
model_keras.add(Dense(1))
model_keras.add(Activation('sigmoid'))

In [79]:
model_keras.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_11 (Dense)             (None, 8)                 24        
_________________________________________________________________
activation_11 (Activation)   (None, 8)                 0         
_________________________________________________________________
dense_12 (Dense)             (None, 1)                 9         
_________________________________________________________________
activation_12 (Activation)   (None, 1)                 0         
Total params: 33
Trainable params: 33
Non-trainable params: 0
_________________________________________________________________


In [0]:
sgd = SGD(lr=0.1)
model_keras.compile(loss='binary_crossentropy', optimizer=sgd)

In [81]:
model_keras.fit(X, y, batch_size=1, nb_epoch=1000)
print(model_keras.predict_proba(X))

/usr/local/lib/python3.6/dist-packages/keras/models.py:981: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


Epoch 1/1000
4/4 [==============================] - 0s 62ms/step - loss: 0.7928
Epoch 2/1000
4/4 [==============================] - 0s 3ms/step - loss: 0.7776
Epoch 3/1000
4/4 [==============================] - 0s 2ms/step - loss: 0.7645
Epoch 4/1000
4/4 [==============================] - 0s 2ms/step - loss: 0.7533
Epoch 5/1000
4/4 [==============================] - 0s 2ms/step - loss: 0.7454
Epoch 6/1000
4/4 [==============================] - 0s 3ms/step - loss: 0.7395
Epoch 7/1000
4/4 [==============================] - 0s 3ms/step - loss: 0.7320
Epoch 8/1000
4/4 [==============================] - 0s 3ms/step - loss: 0.7294
Epoch 9/1000
4/4 [==============================] - 0s 3ms/step - loss: 0.7250
Epoch 10/1000
4/4 [==============================] - 0s 3ms/step - loss: 0.7208
Epoch 11/1000
4/4 [==============================] - 0s 3ms/step - loss: 0.7164
Epoch 12/1000
4/4 [==============================] - 0s 3ms/step - loss: 0.7166
Epoch 13/1000
4/4 [=============================

In [84]:
%time model_keras.predict(X)

CPU times: user 471 µs, sys: 2.16 ms, total: 2.63 ms
Wall time: 5.72 ms


array([[1.5103374e-02],
       [9.9822468e-01],
       [9.9802482e-01],
       [9.9419698e-04]], dtype=float32)

In [0]:
from os import path
from wheel.pep425tags import get_abbr_impl, get_impl_ver, get_abi_tag
platform = '{}{}-{}'.format(get_abbr_impl(), get_impl_ver(), get_abi_tag())

accelerator = 'cu80' if path.exists('/opt/bin/nvidia-smi') else 'cpu'

!pip install -q http://download.pytorch.org/whl/{accelerator}/torch-0.3.0.post4-{platform}-linux_x86_64.whl torchvision

In [0]:
##################
PYTORCH
#################
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F	
import torch.optim as optim
from torch.autograd import Variable

In [0]:
X = np.array([[0,0], [0,1], [1,0], [1,1]])
y = np.array([[0,1,1,0]]).T

In [0]:
#have to pass tensors only
X_tensor = torch.FloatTensor(X)
y_tensor = torch.FloatTensor(y)

In [0]:
inputs = Variable(X_tensor)
labels = Variable(y_tensor, requires_grad=False)

In [0]:
model = nn.Sequential(nn.Linear(2, 8),    
                      nn.ReLU(),       
                      nn.Linear(8, 1),
                      nn.Sigmoid())

In [0]:
criterion = nn.BCELoss()

In [0]:
optimizer = optim.SGD(model.parameters(), lr=0.1)
num_epochs = 1000

In [75]:
for epoch in range(num_epochs):
    predictions = model(inputs)
    loss = criterion(predictions, labels)
    model.zero_grad()
    loss.backward()
    optimizer.step()
    if epoch%100 == 0: 
      print([float(_pred) for _pred in predictions], list(map(int, labels)), loss.data[0])

[0.4746641218662262, 0.4859861135482788, 0.5229929089546204, 0.5811278820037842] [0, 1, 1, 0] 0.7209174036979675
[0.49333006143569946, 0.4973435401916504, 0.5275725722312927, 0.4496158957481384] [0, 1, 1, 0] 0.6537443995475769
[0.514513373374939, 0.5382732152938843, 0.6259409785270691, 0.32565757632255554] [0, 1, 1, 0] 0.5511272549629211
[0.4907122552394867, 0.5955989956855774, 0.7830163240432739, 0.18532675504684448] [0, 1, 1, 0] 0.4106249213218689
[0.41890648007392883, 0.7128747701644897, 0.8715899586677551, 0.1202210858464241] [0, 1, 1, 0] 0.286703497171402
[0.31210803985595703, 0.826449990272522, 0.9100961089134216, 0.08537395298480988] [0, 1, 1, 0] 0.1870461106300354
[0.22128570079803467, 0.8921208381652832, 0.9345906376838684, 0.05621367320418358] [0, 1, 1, 0] 0.12244171649217606
[0.15679463744163513, 0.9263889193534851, 0.9509114623069763, 0.03963780403137207] [0, 1, 1, 0] 0.0844462513923645
[0.11457167565822601, 0.9465689063072205, 0.9632899165153503, 0.030213866382837296] [0, 

In [85]:
%time model(inputs)

CPU times: user 0 ns, sys: 1.55 ms, total: 1.55 ms
Wall time: 1.29 ms


Variable containing:
 0.0666
 0.9671
 0.9771
 0.0192
[torch.FloatTensor of size 4x1]