Note: This nb is meant to be semi-self introductory. Some parts that are vague have to be experimented and found out by the user. Feel free to use this notebook as you wish too.

This provides a brief introduction to Numpy. Futher exploration is up to you 

Import Numpy

In [1]:
import numpy as np

Creating Lists

In [2]:
my_list = [1,2,3]
my_list

[1, 2, 3]

Convert List to Array

In [3]:
np.array(my_list)

array([1, 2, 3])

Creating multi dimensional vectors

In [4]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

Converting my_matrix to Numpy Array

In [5]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Arange is used to generate numbers between the range specified
Mind the single r

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Another varient with the step size mentioned

In [7]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

Zeroes is used to create an array with 0 as values

In [8]:
np.zeros(3)

array([ 0.,  0.,  0.])

Multi-dimensional

In [9]:
np.zeros((5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

np.ones() is used to create an array with all values set to 1.

In [10]:
np.ones(3)

array([ 1.,  1.,  1.])

Multi Dimensional Example

In [11]:
np.ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

np.linspace() is used to create a linearly spaced array

In [12]:
np.linspace(0,10,3)

array([  0.,   5.,  10.])

Multi Dimensional example

In [13]:
np.linspace(0,10,50)

array([  0.        ,   0.20408163,   0.40816327,   0.6122449 ,
         0.81632653,   1.02040816,   1.2244898 ,   1.42857143,
         1.63265306,   1.83673469,   2.04081633,   2.24489796,
         2.44897959,   2.65306122,   2.85714286,   3.06122449,
         3.26530612,   3.46938776,   3.67346939,   3.87755102,
         4.08163265,   4.28571429,   4.48979592,   4.69387755,
         4.89795918,   5.10204082,   5.30612245,   5.51020408,
         5.71428571,   5.91836735,   6.12244898,   6.32653061,
         6.53061224,   6.73469388,   6.93877551,   7.14285714,
         7.34693878,   7.55102041,   7.75510204,   7.95918367,
         8.16326531,   8.36734694,   8.57142857,   8.7755102 ,
         8.97959184,   9.18367347,   9.3877551 ,   9.59183673,
         9.79591837,  10.        ])

In [14]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

np.random.rand() is used to create random numbered arrays (range from 0-1)

In [15]:
np.random.rand(2)

array([ 0.40488309,  0.46652931])

Multi Dimensional example

In [16]:
np.random.rand(5,5)

array([[ 0.14446842,  0.96479017,  0.37574907,  0.45794865,  0.22639021],
       [ 0.93842155,  0.4054823 ,  0.7991733 ,  0.08122208,  0.17594805],
       [ 0.04356338,  0.08401733,  0.39358461,  0.0186519 ,  0.49576109],
       [ 0.74018895,  0.02937591,  0.32805022,  0.38031188,  0.77648835],
       [ 0.10627713,  0.64205336,  0.7522886 ,  0.11934037,  0.12499006]])

np.random.randn()
Press Shift+tab to find the difference between rand() and randn()

In [17]:
np.random.randn(2)

array([ 1.10340351, -0.16465589])

In [18]:
np.random.randn(5,5)

array([[ 0.14118108, -0.56135566, -0.55668215, -1.16960699,  0.18560352],
       [ 1.66672119,  0.07890495, -1.88615004,  2.02244644,  0.03415107],
       [ 0.75191351, -0.89115214,  0.68166528, -0.39473809, -1.45124926],
       [ 0.85715811, -2.87886074, -1.04106559, -0.56522974, -2.42867442],
       [ 1.90411863, -2.18647618, -0.47940531,  1.51818957,  0.37458558]])

randint() returns a random integer from the range specified

In [19]:
np.random.randint(1,100)

80

To return more than one integeres

In [20]:
np.random.randint(1,100,10)

array([11, 99, 82, 71, 50, 51, 24, 33, 47,  1])

In [21]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [22]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [23]:
ranarr

array([32, 36,  5,  3, 26, 35, 46,  8, 40, 12])

reshape() is used to reshape() the array into the desired shape

In [24]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [25]:
ranarr

array([32, 36,  5,  3, 26, 35, 46,  8, 40, 12])

In [26]:
ranarr.max()

46

max() and argmax() return the maximum value and it's index

In [27]:
ranarr.argmax()

6

min() is used to return the minimum value

In [28]:
ranarr.min()

3

In [29]:
ranarr.argmin()

3

.shape is an attribute of Numpy Objects that is used to display the shape of the object.

In [30]:
# Vector
arr.shape

(25,)

In [31]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24]])

In [32]:
arr.reshape(1,25).shape

(1, 25)

In [33]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [34]:
arr.reshape(25,1).shape

(25, 1)

You can check the type by checking the .dtype attribute

In [35]:
arr.dtype

dtype('int64')

In [36]:
#Creating sample array
arr = np.arange(0,11)

In [37]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Accessing index values

In [38]:
#Get a value at an index
arr[8]

8

Slicing. starting pos:Finalpos-1

In [39]:
#Get values in a range
arr[1:5]

array([1, 2, 3, 4])

In [40]:
#Get values in a range
arr[0:5]

array([0, 1, 2, 3, 4])

In [41]:
#Setting a value with index range (Broadcasting)
arr[0:5]=100

#Show
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [42]:
# Reset array, we'll see why I had to reset in  a moment
arr = np.arange(0,11)

#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
#Important notes on Slices
slice_of_arr = arr[0:6]

#Show slice
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [44]:
#Change Slice
slice_of_arr[:]=99

#Show Slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [45]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [46]:
#To get a copy, need to be explicit
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [47]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [48]:
#Indexing row
arr_2d[1]

array([20, 25, 30])

In [49]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0]

20

In [50]:
# Getting individual element value
arr_2d[1,0]

20

In [51]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [52]:
#Shape bottom row
arr_2d[2]

array([35, 40, 45])

In [53]:
#Shape bottom row
arr_2d[2,:]

array([35, 40, 45])

In [54]:
#Set up matrix
arr2d = np.zeros((10,10))

In [55]:
#Length of array
arr_length = arr2d.shape[1]

In [56]:
#Set up array

for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [ 9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.]])

In [57]:
arr2d[[2,4,6,8]]

array([[ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.]])

In [58]:
#Allows in any order
arr2d[[6,4,2,7]]

array([[ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.]])

In [59]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [60]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,  True], dtype=bool)

In [61]:
bool_arr = arr>4

In [62]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,  True], dtype=bool)

In [63]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [64]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [65]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [66]:
arr = np.arange(0,10)

In [67]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [68]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [69]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [70]:
# Warning on division by zero, but not an error!
# Just replaced with nan
arr/arr

/Applications/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([ nan,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.])

In [71]:
# Also warning, but not an error instead infinity
1/arr

/Applications/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([        inf,  1.        ,  0.5       ,  0.33333333,  0.25      ,
        0.2       ,  0.16666667,  0.14285714,  0.125     ,  0.11111111])

In [72]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [73]:
#Taking Square Roots
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ])

In [74]:
#Calcualting exponential (e^)
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03])

In [75]:
np.max(arr) #same as arr.max()

9

In [76]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [77]:
np.log(arr)

/Applications/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([       -inf,  0.        ,  0.69314718,  1.09861229,  1.38629436,
        1.60943791,  1.79175947,  1.94591015,  2.07944154,  2.19722458])